language: objective-c
#before_install:
#    - brew update
#    - brew install xctool
osx_image: xcode7.2
script: xctool -project Transparent\ Image\ Viewer.xcodeproj -scheme Transparent\ Image\ Viewer test
